### import libs

In [16]:
from predict.predict import *
% load_ext autoreload
% autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### init model

In [21]:
model_predict = YOLO_PREDICT(gpu = "0")

darknet
(?, 608, 608, 3)


### gen test data

In [22]:
img_resize = cfg.train.image_resized
image_test = Image.open('dog.jpg')
resized_image = image_test.resize((img_resize, img_resize), Image.BICUBIC)
image_data1 = np.array(resized_image, dtype='float32')

image_test = Image.open('test.jpg')
resized_image = image_test.resize((img_resize, img_resize), Image.BICUBIC)
image_data2 = np.array(resized_image, dtype='float32')

image_data = np.stack((image_data2, image_data1,image_data2, image_data1, image_data2))
print(image_data.shape)

(5, 608, 608, 3)


### do predict

In [26]:
img_id_list = ["0", "1", "2", "3", "4"]
model_predict.predict_imgs(image_data, img_id_list)

INFO:tensorflow:Restoring parameters from ./ckpt/yolov3.ckpt-50001


In [31]:
for img_id in img_id_list:
    print("#img_id is %s#" % img_id)
    print(model_predict.boxes_dict[img_id])
    print(model_predict.scores_dict[img_id])
    print(model_predict.classes_dict[img_id])

#img_id is 0#
[[ 236.95947266   99.02166748  418.59063721  299.2911377 ]
 [  72.08097839  123.57663727  403.97561646  415.80300903]
 [ 356.80581665  382.77346802  557.71008301  608.        ]
 [ 133.46351624    0.          423.10681152  215.12161255]
 [ 432.91235352   67.78265381  608.          276.55718994]]
[ 0.93634534  0.81332016  0.65029818  0.64678603  0.35471582]
[2 3 4 2 4]
#img_id is 1#
[[ 181.70236206  140.17556763  423.50167847  353.73834229]
 [ 423.25415039   75.34571838  608.          209.12716675]]
[ 0.61964929  0.34239063]
[4 3]
#img_id is 2#
[[ 236.95947266   99.02166748  418.59063721  299.2911377 ]
 [  72.08097839  123.57663727  403.97561646  415.80300903]
 [ 356.80581665  382.77346802  557.71008301  608.        ]
 [ 133.46351624    0.          423.10681152  215.12161255]
 [ 432.91235352   67.78265381  608.          276.55718994]]
[ 0.93634534  0.81332016  0.65029818  0.64678603  0.35471582]
[2 3 4 2 4]
#img_id is 3#
[[ 181.70236206  140.17556763  423.50167847  353.7383